### ISSUE TITLE
[Bug] Biometrics Can be bypassed by tapping outside of the area

### ISSUE THREAD

**Issue by SnakeOverflow** [Pool-Of-Tears/GreenStash#11]
When setting up biometrics  it will prompt you upon opening and will work like normal, but after testing a bit I've found out that simply tapping outside the area will let you bypass the login entirely. Ive added a clip of the process

https://user-images.githubusercontent.com/109717184/180974129-a20cd503-bd04-4277-a51e-fe46d43bf90b.mp4

Maybe this can be fix by having the app wait on the splash screen, or having the app wait in a separate screen with the logo and a button to re-prompt for biometrics, until the apps detects a successful auth?

**Comment by starry69** [comment]
Can confirm, that's a serious bug imo.

> Maybe this can be fix by having the app wait on the splash screen, or having the app wait in a separate screen with the logo and a button to re-prompt for biometrics, until the apps detects a successful auth?

Actually when you tap outside of area and auth fails the app should close itself automatically, i think it's caused due to [this](https://github.com/Pool-Of-Tears/GreenStash/blob/618ebc2fd62d58c329b429122c57c846a289e90c/app/src/main/java/com/starry/greenstash/MainActivity.kt#L122), I'll try to investigate and release an update after fixing it asap. Thank-you so much for reporting!
