### ISSUE TITLE
[Feature Request] Adjust Amount Instead Of Using Depost/Withdraw

### ISSUE THREAD

**Issue by seniorm0ment** [Pool-Of-Tears/GreenStash#39]
An option to simply adjust the current amount, instead of forcing the user to do through depositing and withdrawing would be nice.

This makes it a little easier to deal with deposits that are technically interest gains. So instead of going and looking at the amount that the bank deposited in interest, you can quickly just look at the total in the account, and then change the amount on GreenStash to that exact amount.

**Comment by starry-shivam** [comment]
The deposit/withdraw mechanism allows us to have a record of transactions, how you're suggesting this adjusting thing will work like how the interface should be implemented?

Btw you can also just add interest gains as another deposit, because in the next update I'm planning to add ability to have remarks/notes in transactions so it should make it more clearer.

For example: let's say you add 100$ which is an interest gain as a new deposit and add something like "Interest gains" as a remark on the said transaction and it'll also show up in the goal information screen.

Lemme know if this works.

**Comment by starry-shivam** [comment]
Linking same comment for same reason
https://github.com/Pool-Of-Tears/GreenStash/issues/38#issuecomment-1571203844

**Comment by seniorm0ment** [comment]
Interest gains as another deposit would work. It's just a bit more tedious to have to go and confirm which interest gains you already deposited and didn't. Being able to just adjust the total would be a simple way to "override" any mistakes when depositing/withdrawing. 

Of course this would negate the use of transactions for that goal. But if the user doesn't care about seeing the transactions record for this then it wouldn't matter. It could just show as  -1200 +$1500. Like a full withdraw then a full deposit. 

I get it doesn't make a ton of sense, it's just a abstract convenience thing so I understand if this one isn't considered.
