### ISSUE TITLE
[Feature Request] pick goal images over gallery / file manager

### ISSUE THREAD

**Issue by bloodyeyesblackblood** [Pool-Of-Tears/GreenStash#62]
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [ ] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

first off, i like the app design, great job <3

so, if i wanna set a goal image, only few are shown, some are missing (somehow those albums that aren't shown are ones with cutsom name).

only shows camera, screenshots & downloads — if i move a image there, it does show up~

### Describe the solution you'd like

open and select over an gallery app / file manager?

### How will you/everyone benefit from this feature?

the ppl who already benefit from usin' goal images

### Additional context

well nvmnd, i'm blind, all images DO SHOW UP in "photos" but when havin' a lot of images it's confusing. so it might be a bug that all albums don't  show up in the albums tab?

**Comment by starry-shivam** [comment]
You see, the current photo picker uses [Android's new photo picker](https://developer.android.com/training/data-storage/shared/photopicker) implementation introduced with A13. It is designed in such a way that apps won't have to ask for read storage permission since the app only gets access to photos you explicitly select, instead of being able to read your entire gallery. That's basically why I'm using it, as it saves me the hurdle of making my own custom implementation (which would also require permission to read external storage) and is better for users' privacy as well.

Regarding the issue of all albums not showing up, I don't think I can do much about that since the photo picker is controlled entirely by the Android OS itself. I can only request the system to show the photo picker and then get information about the images the user has selected. I can't really control or modify how it works.

**Comment by bloodyeyesblackblood** [comment]
aww i see~ thanks <3
well idk if google is gonna fix/enhance this.. i don't think so, it's just pain :(

**Comment by bloodyeyesblackblood** [comment]
idk could thos help? https://www.reddit.com/r/reactnative/comments/17svot0/comment/k8wy737/ can't remember that there was a permission in your app for accesing all media? (would this make a difference?) even in permission theres only "notification"
