### ISSUE TITLE
[Feature Request] Import data from other apps / import CSV

### ISSUE THREAD

**Issue by Myzel394** [Pool-Of-Tears/GreenStash#77]
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [ ] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

I'm currently using [Paisa](https://github.com/RetroMusicPlayer/Paisa) to manage my expenses. However, I wanted to give this app a try, since it looks pretty awesome at first sight! :)

However, since I'm using Paisa for quite some time now, it'd take an enormous effort to manually enter everything into GreenStash.

### Describe the solution you'd like

Paisa offers two ways to export data: CSV and JSON.

I guess there are also a lot of people that will manage their expenses without any app and instead by hand in a CSV file. Therefore I propose to add support to import data from other apps (such as Paisa) plus a general CSV importer.

### How will you/everyone benefit from this feature?

It will be easier for new users to migrate their stuff to GreenStash! :D

### Additional context

I can provide you a sample exported Paisa file

**Comment by starry-shivam** [comment]
First of all, thank you for showing interest in Greenstash. Regarding the general CSV import and export functionality, along with JSON, it seems totally doable. However, importing backups from another app isn't something that would be reliable, as I can't guarantee that their backup would always follow the same structure as I've integrated them right now. This means I'll constantly have to monitor the source code of a bunch of other apps to track changes in their export schema and continuously update my import functionality. 

Additionally, there's another issue. Take Paisa, for example. It's a full-fledged expense tracking application, whereas Greenstash is an app designed for tracking savings by setting saving goals. The scopes of both applications are entirely different, as are their databases. This, combined with the aforementioned reason, makes it even less sensible to have such a functionality. I believe this app can be used as a complementary tool with your favorite expense tracker instead of replacing it, as Greenstash isn't an expense tracker in the first place. Adding the ability to import data from expense tracker apps doesn't really make much sense here; it'll just add to the burden of maintainability with no guarantee of success.

**Comment by starry-shivam** [comment]
Closing due to no response from author.
